spring.application.name=sb-ecom
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
project.image=images/
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.app.jwtSecret=ujdasgdihlSECRETkasdas54756a7467654we6d4sadf4ad6a4sd6as7dfasdf4af6as4fd6as4dfa
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookie=springBootEcom