spring.application.name=sb-ecom
# h2 DATABASE CONFIGURATION
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.h2.console.enabled=true
#  MY SQL DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
project.image=images/
spring.app.jwtSecret=ujdasgdihlSECRETkasdas54756a7467654we6d4sadf4ad6a4sd6as7dfasdf4af6as4fd6as4dfa
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookie=springBootEcom